apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: enesdemir09/k8s-collector:latest # Change this!
        imagePullPolicy: IfNotPresent # Tells K8s to use the image we just "loaded"
        env:
        - name: SYMBOL
          value: "bitcoin"
        - name: FETCH_INTERVAL  # Bu satırı ekle
          value: "60"           # Bu değeri 60 yap
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"